spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test  # ✅ 인메모리 H2 DB (테스트용)
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10  # ✅ HikariCP 커넥션 풀 설정 (최대 10개)

  jpa:
    hibernate:
      ddl-auto: update  # ✅ 기존 데이터 유지 (테스트에서는 create도 가능)
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect  # ✅ H2 전용 다이얼렉트 설정


logging:
  level:
    org.hibernate.SQL: debug  # ✅ 실행되는 SQL 출력
    org.hibernate.orm.jdbc.bind: trace  # ✅ SQL 실행 시 바인딩된 값 출력
